camel:
  servlet:
    mapping:
      context-path: /gateway/*

server:
  port:
    8081

url:
  base-endpoint: http://localhost:8080
  technology: /technology/technologies
  message: /add/message
  messages: /list/message
  tech: /add/tech



